### ISSUE TITLE
Document how developers can run mypy, ruff, black locally for NanoVer

### ISSUE THREAD

**Issue by Ragzouken** [IRL2/nanover-protocol#104]
Pull requests need to pass CI including type checks and linting, but it's not clear how to run these locally. mypy in particular seems to need to be provided with some information about the package structure of the project? The workflow of having to wait for the CI to drip feed you typing problems and linting issues one by one is frustrating.

**Comment by jbarnoud** [comment]
This indeed needs to be documented. Running mypy is especially tricky and annoying because of mypy partial support for namespace packages.

CI runs mypy this way: https://github.com/IRL2/nanover-protocol/blob/67f7e6d3e3528338159c98d3d68901ac909b6950/.github/workflows/tests.yml#L51

Black is simpler. Black can be installed with `pip install black`. It can be used to reformat all python files by running `black ./python-libraries` from the root of the repo. It can be used to just check the files with `black --diff --check ./python-libraries`.

Ruff is pretty simple as well. `pip install ruff` to install, and `ruff ./python-libraries` to run.
