### ISSUE TITLE
"Address already in use" error when running python tests

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-protocol#96]
When running the python tests, the following test fails (at least on macOS): `test_essd_client_server.py::test_send_service_multiple_clients - OSError [Errno 48] Address already in use`
Running the tests multiple times yields the same results, even though the machine isn't running anything else (as far as I am aware). Each time, the address that is in use changes, but the error persists.

**Comment by jbarnoud** [comment]
This could be related to the SO_REUSE_PORT flag when opening the ESSD socket. At least, it seems related to https://github.com/IRL2/nanover-rs/issues/218 in the rust server.

We have a similar issue on Windows. This issue is a bit different, though: on Windows we cannot have 2 ESSD servers on the same host while it looks like MacOS does not let us have 2 ESSD clients.

**Comment by Ragzouken** [comment]
@hjstroud does this consistently fail for you? Is there a more detailed traceback/log for the failure? What happens if you run just this test in isolation? (`pytest python-libraries/nanover-essd/tests/test_essd_client_server.py::test_send_service_multiple_clients`)

**Comment by hjstroud** [comment]
@Ragzouken This test does consistently fail for me. I have attached a screenshot of the output in the terminal when running this test in isolation:
![Uploading Screenshot 2024-05-09 at 11.49.20.png…]()
